on:
  push:
    branches: [
      main
    ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy RG
      id: deployRG
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope
        template: resourceGroup/rg.json
        parameters: resourceGroup/rg.params.json

    - name: Deploy Maintenance Configuration - Windows Security and Critical Ring 1
      id: deployMaintenanceConfiguration
      uses: azure/arm-deploy@v1
      with: 
        resourceGroupName: ${{ steps.deployRG.outputs.rgName }}
        template: updateManagement/maintenanceConfiguration.json
        parameters: updateManagement/WindowsCriticalSecurityRing1.params.json

    - name: Deploy Maintenance Configuration - Windows Security and Critical Ring 2
      id: deployMaintenanceConfigurationRing2
      uses: azure/arm-deploy@v1
      with: 
        resourceGroupName: ${{ steps.deployRG.outputs.rgName }}
        template: updateManagement/maintenanceConfiguration.bicep